version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - xpack.security.enabled=false